/* eslint-disable max-len */
import React from 'react';
import '../../style/visionStyle.scss';

function DataScienceWorks() {
  return (
    <div className="visionpage">
      <div className="proj mb-2">
        <div className="proj-titel-container"><h3 className="proj-title">Data Science Services</h3></div>
      </div>
      <h3 style={{ marginBottom: '0px' }} className="visionpage-h2 mb-0">
        Camel: Customized
        <span className="highlight"> Large Language Model </span>
        (LLM)
      </h3>
      <p className="vision-text mb-3">
        Personalized AI Assistant for Organizational Insights
      </p>
      <p className="vision-text mb-3">
        Camel is a tailored LLM solution designed to transform how organizations access and utilize their data. With the ability to understand and analyze information across departments, Camel answers complex queries with precision, empowering companies to make data-driven decisions effortlessly.
      </p>
      <h3 style={{ marginBottom: '0px' }} className="visionpage-h2 mb-0">
        Intelligent Video Surveillance
        <span className="highlight"> Video Surveillance </span>
        (IVS)
      </h3>
      <p className="vision-text mb-3">
        AI-Powered Video Surveillance & Analytics
      </p>
      <p className="vision-text mb-3">
        Our IVS system leverages cutting-edge computer vision technology to process multiple video feeds simultaneously, identifying over 80 object classes, human keypoints, and more. From vehicle plate detection to workout tracking and crowd analysis, our solution enhances security with customizable region-specific rules, suspicious object detection, and a comprehensive analytics dashboard.
      </p>
      <h3 style={{ marginBottom: '0px' }} className="visionpage-h2 mb-0">
        CandiJob:
        <span className="highlight"> AI-Powered Recruitment </span>
        Platform
      </h3>
      <p className="vision-text mb-3">
        Intelligent Hiring Platform for Job Seekers & Companies
      </p>
      <p className="vision-text mb-3">
        CandiJop simplifies recruitment through AI. Job seekers can upload their CVs, and our system handles the rest—analyzing resumes, identifying skill gaps, and matching candidates with job openings. For companies, the platform automatically matches candidates to job requirements and provides AI-driven interview analysis and HR insights.
      </p>
      <h3 style={{ marginBottom: '0px' }} className="visionpage-h2 mb-0">
        Port Terminal
        <span className="highlight"> Smart Solutions </span>
      </h3>
      <p className="vision-text mb-3">
        AI Solutions for Smarter Port Operations
      </p>
      <p className="vision-text mb-3">
        Revolutionize port management with our AI-driven solutions. Our platform provides real-time dashboards for monitoring port performance and optimizes operations with models like:
        <ul>
          <li>Vessel Berth Allocation Prediction: Efficiently assign vessels to berths, reducing wait times.</li>
          <li>Vessel Operation Time Analysis: Accurately estimate operational durations for better planning.</li>
          <li>Container Suspicion Prediction: Detect potentially suspicious containers using data from various sources to enhance port security.</li>
        </ul>
      </p>
      <h2 className="visionpage-h2">
        Other fields we
        <span className="highlight"> specialize </span>
        in
      </h2>
      <h3 className="visionpage-h2">
        Marketing
      </h3>
      <img className="vision-img" src="datascience-1.png" alt="datascience-1" />
      <h3 className="visionpage-h2">
        Human
        <span className="highlight"> Resources </span>
      </h3>
      <img className="vision-img" src="datascience-2.png" alt="datascience-2" />
      <h3 className="visionpage-h2">
        Banking
        <span className="highlight"> Services </span>
      </h3>
      <img className="vision-img" src="datascience-3.png" alt="datascience-1" />
      <h3 className="visionpage-h2">
        Educational
      </h3>
      <img className="vision-img" src="datascience-4.png" alt="datascience-1" />
      <h3 className="visionpage-h2">
        Agricultural
      </h3>
      <img className="vision-img" src="datascience-5.png" alt="datascience-1" />

      <h3 className="visionpage-h2">
        Service
        <span className="highlight"> Management </span>
      </h3>
      <img className="vision-img-small" src="datascience-5.png" alt="datascience-1" />
      <h2 className="visionpage-h2 mb-0">
        Internet of
        <span className="highlight"> Things </span>
        (IOT)
      </h2>
      <p className="vision-text mb-3">
        Our company leverages data science to unlock the full potential of the Internet of Things (IoT) by transforming the vast data generated by connected devices into actionable insights. Through advanced analytics and machine learning algorithms, we identify patterns and trends in real-time data, enabling predictive maintenance and informed decision-making for our clients. For instance, in smart home applications, we optimize energy consumption by analyzing usage patterns and offering tailored recommendations for efficiency. Additionally, our solutions enhance smart city initiatives by analyzing traffic data to improve transportation systems and reduce congestion. By harnessing data science for IoT, we empower organizations to achieve improved operational efficiency and deliver enhanced user experiences.
      </p>
    </div>
  );
}
export default DataScienceWorks;
